version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      - db